### ISSUE TITLE
CheckBoxes on Task Dialog

### ISSUE THREAD

**Issue by Krimsondk** [aelij/WPFContrib#3]
I would like to display a CheckBox on the Task Dialog in the area where RadioButtons and CommandLinks are show, but I don't see a way to do this.
Is this possible, or should I do a pull request?

**Comment by aelij** [comment]
I've built `TaskDialog` to match the same capabilities of the one the OS provides, and I would like to keep it this way. However, since it is a WPF control, you can stick any content inside the dialog, for example:

```csharp
var dialog = new TaskDialog
{
    Content = new MyContent(),
    ContentTemplate = TryFindResource("MyContentTemplate") as DataTemplate
};
```

So you can even have a view-model tied to it, and have the template contain any UI elements you need.
